// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjiq9DZ2cr04yWQ-G2yw9APmkXAuQIDvY',
    appId: '1:716323728609:web:9ff4f994d4998580405ba0',
    messagingSenderId: '716323728609',
    projectId: 'cocoatokenflutter',
    authDomain: 'cocoatokenflutter.firebaseapp.com',
    storageBucket: 'cocoatokenflutter.firebasestorage.app',
    measurementId: 'G-FJ0P1SWEP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdHaqRkEI8mtTnFezT_aLFmdp56GP74t8',
    appId: '1:716323728609:android:dbc0e7c66c3783ee405ba0',
    messagingSenderId: '716323728609',
    projectId: 'cocoatokenflutter',
    storageBucket: 'cocoatokenflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGvagRnEFKWRhEs2XRcrEW-6FAPORbd0E',
    appId: '1:716323728609:ios:3e544d8ef304f08a405ba0',
    messagingSenderId: '716323728609',
    projectId: 'cocoatokenflutter',
    storageBucket: 'cocoatokenflutter.firebasestorage.app',
    iosBundleId: 'com.example.cocoaTokenFront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGvagRnEFKWRhEs2XRcrEW-6FAPORbd0E',
    appId: '1:716323728609:ios:3e544d8ef304f08a405ba0',
    messagingSenderId: '716323728609',
    projectId: 'cocoatokenflutter',
    storageBucket: 'cocoatokenflutter.firebasestorage.app',
    iosBundleId: 'com.example.cocoaTokenFront',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjiq9DZ2cr04yWQ-G2yw9APmkXAuQIDvY',
    appId: '1:716323728609:web:5b55b38804c771d6405ba0',
    messagingSenderId: '716323728609',
    projectId: 'cocoatokenflutter',
    authDomain: 'cocoatokenflutter.firebaseapp.com',
    storageBucket: 'cocoatokenflutter.firebasestorage.app',
    measurementId: 'G-3ETETY1P7N',
  );
}
